name: horizontal_gauge
description: A customizable horizontal gauge widget for Flutter with smooth animations, interactive controls, and rich theming options.
version: 2.0.0
homepage: https://github.com/SpinexIO/horizontal_gauge
repository: https://github.com/SpinexIO/horizontal_gauge
issue_tracker: https://github.com/SpinexIO/horizontal_gauge/issues

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
